SERVICE_DNS: clients

server:
  port: 9080

spring:
  application:
    name: service-client
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: ${SERVICE_DNS}
        health-check-interval: 1s
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}:${random.value}