SERVICE_DNS: invoices

server:
  port: 8070

spring:
  application:
    name: service-invoice
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: ${SERVICE_DNS}
        health-check-interval: 1s
        health-check-path: /actuator/health
        instance-id: ${spring.application.name}:${random.value}